Repository SOPT-all/36-COLLABORATION-SERVER-INTERPARK, pull requests merged in 2025-05, with the labels that each got.

#2 Chore/#1 공통 응답 객체 생성 및 전역 예외처리
  build.gradle
  src/main/java/com/interpark/global/dto/ErrorResponse.java
  src/main/java/com/interpark/global/dto/SuccessResponse.java
  src/main/java/com/interpark/global/error/code/ErrorCode.java
  src/main/java/com/interpark/global/error/code/SuccessCode.java
  src/main/java/com/interpark/global/error/exception/BusinessException.java
  src/main/java/com/interpark/global/handler/GlobalExceptionHandler.java
Labels: 재민, 🧩 FEAT

#4 Chore/#3 CorsConfig 추가
  src/main/java/com/interpark/config/CorsConfig.java
Labels: 채륜, 🧩 FEAT

#7 Feat/#5 performance 도메인 생성
  src/main/java/com/interpark/domain/performance/entity/Performance.java
Labels: 채륜, 🧩 FEAT

#10 Feat/#9 결제 수단 도메인 생성
  src/main/java/com/interpark/domain/payment/method/entity/PaymentMethod.java
Labels: 채륜, 🧩 FEAT

#12 Feat/#11 좌석 도메인 생성
  src/main/java/com/interpark/domain/seat/entity/Seat.java
Labels: 채륜, 🧩 FEAT

#14 Feat/#13 결제수단 상세 도메인 생성 및 연관관계 매핑
  src/main/java/com/interpark/domain/payment/method/detail/entity/PaymentMethodDetail.java
Labels: 채륜, 🧩 FEAT

#19 Revert "Feat/#11 좌석 도메인 생성"
  src/main/java/com/interpark/domain/seat/entity/Seat.java
Labels: 채륜, 🚨HOTFIX

#21 Feat/#20 태그 도메인 생성
  src/main/java/com/interpark/domain/tag/entity/Tag.java
Labels: 채륜, 🧩 FEAT

#8 Feat/#6 예매자 도메인 생성
  src/main/java/com/interpark/domain/user/entity/User.java
Labels: 채륜, 🧩 FEAT

#23 Feat/#22 공연별 태그 도메인 생성
  src/main/java/com/interpark/domain/performancetag/entity/PerformanceTag.java
Labels: 채륜, 🧩 FEAT

#25 Feat/#20 공연별 태그 도메인 생성
  src/main/java/com/interpark/domain/performancetag/entity/PerformanceTag.java
Labels: 채륜, 🧩 FEAT

#26 Feat/#6 예매자 도메인 생성
  src/main/java/com/interpark/domain/user/entity/User.java
Labels: 채륜, 🧩 FEAT

#30 Feat/#11 좌석 도메인 생성
  src/main/java/com/interpark/domain/seat/entity/Seat.java
Labels: 채륜, 🧩 FEAT

#31 Feat/#29 좌석 정보 도메인 생성
  src/main/java/com/interpark/domain/seat/detail/entity/SeatDetail.java
  src/main/java/com/interpark/domain/seat/entity/Seat.java
Labels: 채륜, 🧩 FEAT

#28 Feat/#27 예매 정보 도메인 생성
  src/main/java/com/interpark/domain/reservation/entity/Reservation.java
  src/main/java/com/interpark/domain/seat/detail/entity/SeatDetail.java
Labels: 채륜, 🧩 FEAT

#40 Feat/#32 좌석 상태 조회 기능 생성
  .gitignore
  src/main/java/com/interpark/domain/seat/detail/controller/SeatDetailController.java
  src/main/java/com/interpark/domain/seat/detail/dto/SeatResponse.java
  src/main/java/com/interpark/domain/seat/detail/dto/SeatRowDto.java
  src/main/java/com/interpark/domain/seat/detail/repository/SeatDetailRepository.java
  src/main/java/com/interpark/domain/seat/detail/service/SeatDetailService.java
  src/main/java/com/interpark/domain/seat/entity/Seat.java
  src/main/java/com/interpark/domain/seat/repository/SeatRepository.java
Labels: 채륜, 🧩 FEAT

#46 Feat/#44 날짜에 맞는 공연 정보 조회 기능 생성
  .gitignore
  src/main/java/com/interpark/domain/seat/detail/controller/SeatDetailController.java
  src/main/java/com/interpark/domain/seat/detail/dto/DateResponse.java
  src/main/java/com/interpark/domain/seat/detail/dto/PerformanceDto.java
  src/main/java/com/interpark/domain/seat/detail/dto/SeatGradeDto.java
  src/main/java/com/interpark/domain/seat/detail/repository/SeatDetailRepository.java
  src/main/java/com/interpark/domain/seat/detail/service/SeatDetailService.java
  src/main/resources/static/images/poster001.png
Labels: 채륜, 🧩 FEAT

#61 Fix/#60 상태 변화 추가
  src/main/java/com/interpark/domain/seat/detail/controller/SeatDetailController.java
  src/main/java/com/interpark/domain/seat/detail/entity/SeatDetail.java
  src/main/java/com/interpark/domain/seat/detail/service/SeatDetailService.java
Labels: 채륜, 🛠️FIX
